const MODELS = [
  {
    model: "Stable Diffusion 3.5",
    developer: "Stability AI",
    year: "2024",
    modality: "Image",
    io: "Text/Image → Image",
    licenseType: "Restricted-Open",
    licenseName: "Stability AI Community License",
    dataDisclosed: "No",
    dataSources: "LAION-5B subset + proprietary data; specific composition undisclosed",
    attribution: "None",
    commercialUse: "Yes (<$1M revenue)",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "PNG, JPG, WebP",
    openSource: "Yes",
    dataGap: "Training data sourced from web scrape without creator consent; no attribution tool; revenue threshold gate",
    notes: "Most widely deployed open image model. LAION dataset faced copyright lawsuits (Getty v. Stability AI).",
    workflow: { folder: "Stable Diffusion 35", json: "StableDiffusion35.json", image: "SD35_output_00001_.png" }
  },
  {
    model: "FLUX.1 (Schnell/Dev)",
    developer: "Black Forest Labs",
    year: "2024",
    modality: "Image",
    io: "Text → Image",
    licenseType: "Mixed",
    licenseName: "Apache 2.0 (Schnell); Non-commercial (Dev); Proprietary (Pro)",
    dataDisclosed: "No",
    dataSources: "Undisclosed; founded by ex-Stability AI team",
    attribution: "None",
    commercialUse: "Yes (Schnell only)",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "PNG, JPG, WebP",
    openSource: "Yes",
    dataGap: "Apache Schnell variant is open but training data fully undisclosed; split licensing model creates confusion",
    notes: "State-of-the-art quality in 2024-25. Schnell = best open image model. Data provenance = black box.",
    workflow: { folder: "FLUX.1", json: "Flux1.json", image: "FLUX1_output_00001_.png" }
  },
  {
    model: "Stable Diffusion XL",
    developer: "Stability AI",
    year: "2023",
    modality: "Image",
    io: "Text/Image → Image",
    licenseType: "Restricted-Open",
    licenseName: "CreativeML Open RAIL-M",
    dataDisclosed: "Partial",
    dataSources: "LAION-5B (partially documented) + additional proprietary data",
    attribution: "None (LAION documented sources but no per-image attribution)",
    commercialUse: "Yes (with attribution)",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "PNG, JPG, SafeTensors, GGUF",
    openSource: "Yes",
    dataGap: "RAIL-M restricts harmful use but no attribution for training artists; LAION lawsuit pending",
    notes: "RAIL-M was first attempt at responsible use license for diffusion models. Key reference.",
    workflow: { folder: "Stable Diffusion XL", json: "StableDiffusionXL.json", image: "SDXL_output_00001_.png" }
  },
  {
    model: "DeepFloyd IF",
    developer: "Stability AI / DeepFloyd",
    year: "2023",
    modality: "Image",
    io: "Text → Image",
    licenseType: "Restricted-Open",
    licenseName: "DeepFloyd IF Research License",
    dataDisclosed: "No",
    dataSources: "LAION-5B + Conceptual Captions",
    attribution: "None",
    commercialUse: "No",
    finetune: "Partial",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "PNG",
    openSource: "Yes",
    dataGap: "Research-only license; LAION data issues; cascade model requires significant compute",
    notes: "Pioneered pixel-space cascade diffusion. Research-only use limits applicability."
  },
  {
    model: "StyleGAN / StyleGAN3",
    developer: "NVIDIA",
    year: "2019-2021",
    modality: "Image",
    io: "Latent → Image (face-specialized)",
    licenseType: "Restricted-Open",
    licenseName: "NVIDIA Source Code License",
    dataDisclosed: "Partial",
    dataSources: "FFHQ (Flickr Faces HQ - scraped Flickr); LSUN; AFHQ",
    attribution: "FFHQ dataset published with provenance; faces from Flickr under CC license",
    commercialUse: "Partial",
    finetune: "Partial",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "PNG, TFRecord",
    openSource: "Yes",
    dataGap: "Flickr data scraped without explicit AI consent; faces of real people; NVIDIA non-commercial clauses",
    notes: "Best-in-class for photorealistic faces. FFHQ documentation = good data provenance example."
  },
  {
    model: "AnimateDiff",
    developer: "Shanghai AI Lab",
    year: "2023",
    modality: "Video",
    io: "Text/Image → Video",
    licenseType: "Permissive",
    licenseName: "Apache 2.0",
    dataDisclosed: "No",
    dataSources: "WebVid-10M + internal data; sources partially cited",
    attribution: "None",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MP4, GIF",
    openSource: "Yes",
    dataGap: "Training data partially cited but no attribution; runs on SD base = inherits SD data issues",
    notes: "Plug-in motion module for SD. Apache license but inherits Stable Diffusion data IP issues."
  },
  {
    model: "Open-Sora (HPC-AI Tech)",
    developer: "HPC-AI Tech",
    year: "2024",
    modality: "Video",
    io: "Text → Video",
    licenseType: "Fully Open",
    licenseName: "Apache 2.0",
    dataDisclosed: "Full",
    dataSources: "HD-VG-130M, Panda-70M, WebVid-10M - all documented",
    attribution: "Dataset documentation published; sources cited",
    commercialUse: "Full",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MP4",
    openSource: "Yes",
    dataGap: "WebVid license restricts commercial use of trained models; data source mix has IP complexity",
    notes: "Most transparent open video model. Data docs set a good standard despite licensing mix."
  },
  {
    model: "Wan 2.1 (Alibaba)",
    developer: "Alibaba",
    year: "2025",
    modality: "Video",
    io: "Text/Image → Video",
    licenseType: "Permissive",
    licenseName: "Apache 2.0",
    dataDisclosed: "No",
    dataSources: "Undisclosed",
    attribution: "None",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MP4",
    openSource: "Yes",
    dataGap: "Complete data opacity despite Apache license; state-of-the-art video quality",
    notes: "Best open video model quality as of early 2025. Data provenance entirely opaque."
  },
  {
    model: "MusicGen (Meta)",
    developer: "Meta AI",
    year: "2023",
    modality: "Audio",
    io: "Text/Melody → Music",
    licenseType: "Restricted-Open",
    licenseName: "CC BY-NC 4.0",
    dataDisclosed: "Partial",
    dataSources: "Licensed music dataset (~20K hours; licensed tracks, not public domain)",
    attribution: "Dataset of licensed music used; license holder list partially disclosed",
    commercialUse: "Partial",
    finetune: "No",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "WAV, MP3",
    openSource: "Yes",
    dataGap: "NC license; dataset included licensed tracks - sets precedent for licensed training data model; no per-track attribution output",
    notes: "Key precedent: used properly licensed training data. NC restriction is limiting. Good model card."
  },
  {
    model: "AudioCraft / EnCodec",
    developer: "Meta AI",
    year: "2023",
    modality: "Audio",
    io: "Text → Audio/Music",
    licenseType: "Restricted-Open",
    licenseName: "CC BY-NC 4.0",
    dataDisclosed: "Partial",
    dataSources: "AudioSet, FreeSound, Shutterstock (licensed); some unlicensed web audio",
    attribution: "Partial source list; no per-sample attribution",
    commercialUse: "Partial",
    finetune: "No",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "WAV, encodec tokens",
    openSource: "Yes",
    dataGap: "NC license limits commercial use; mixed licensed/unlicensed training data; no attribution output",
    notes: "Best open music generation pipeline. NC + mixed data provenance = key gap for commercial projects."
  },
  {
    model: "Dance Diffusion (Harmonai)",
    developer: "Harmonai / Stability AI",
    year: "2022",
    modality: "Audio",
    io: "Audio → Audio",
    licenseType: "Fully Open",
    licenseName: "MIT",
    dataDisclosed: "Full",
    dataSources: "Online sources: glitch.cool, songaday.world, MAESTRO, Unlocked Recordings, xeno-canto",
    attribution: "All sources listed in documentation",
    commercialUse: "Full",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "WAV",
    openSource: "Yes",
    dataGap: "Source list published but consent status unclear for scraped sites; no output attribution",
    notes: "MIT license + documented sources = good model. Matches gen-ai-for-music.alwaysdata.net entry."
  },
  {
    model: "RAVE (IRCAM)",
    developer: "IRCAM / Antoine Caillon",
    year: "2022",
    modality: "Audio",
    io: "Audio → Audio (realtime VAE)",
    licenseType: "Fully Open",
    licenseName: "MIT",
    dataDisclosed: "Full",
    dataSources: "User-provided (train on your own data); no fixed dataset",
    attribution: "User controls training data - strongest possible attribution model",
    commercialUse: "Full",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "WAV, Max/MSP, PureData",
    openSource: "Yes",
    dataGap: "Train-your-own model: user must ensure their data rights. No centralized dataset = no centralized IP issue.",
    notes: "Excellent model for artists training on their own archives. Fits project ethos perfectly."
  },
  {
    model: "AudioLCM",
    developer: "University researchers",
    year: "2023",
    modality: "Audio",
    io: "Text → Audio",
    licenseType: "Fully Open",
    licenseName: "MIT",
    dataDisclosed: "Partial",
    dataSources: "AudioCaps dataset + undisclosed teacher model",
    attribution: "AudioCaps documented; teacher model not disclosed",
    commercialUse: "Partial",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "WAV",
    openSource: "Yes",
    dataGap: "Teacher model provenance unknown; otherwise well-documented",
    notes: "Efficient latent consistency model. Good starting point for licensed audio generation."
  },
  {
    model: "Stable Audio Open",
    developer: "Stability AI",
    year: "2024",
    modality: "Audio",
    io: "Text → Audio/Music",
    licenseType: "Fully Open",
    licenseName: "Apache 2.0",
    dataDisclosed: "Partial",
    dataSources: "Freesound dataset (~800K clips, Creative Commons licensed)",
    attribution: "Freesound = CC-licensed, documented; metadata retained in dataset",
    commercialUse: "Partial",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "WAV, FLAC",
    openSource: "Yes",
    dataGap: "Freesound CC licenses vary (some NC, some commercial) - aggregate license unclear; no per-output attribution",
    notes: "Key model: trained on CC-licensed audio. Closest to ethically-sourced generative audio for this project."
  },
  {
    model: "Aimi",
    developer: "aimi.fm",
    year: "2023",
    modality: "Audio",
    io: "Text → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "Aimi is a royalty-free AI music generator built for creators, advertisers and app developers who need broadcast-safe soundtracks and live streams, instantly. (Length: Endless · Real-time)"
  },
  {
    model: "AIVA",
    developer: "aiva.ai",
    year: "2019",
    modality: "Audio",
    io: "Audio/MIDI → Audio/MIDI",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio/MIDI",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "AIVA is an AI music generation assistant that allows you to generate new songs in more than 250 different styles, in a matter of seconds. Whether a complete beginner or a seasoned professional in music making, use the power of generative AI to create your own songs. (Length: 5:30)"
  },
  {
    model: "Amadeus Code App",
    developer: "amadeuscode.com",
    year: "2019",
    modality: "Audio",
    io: "Genre → Audio/MIDI",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio/MIDI",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "AI-powered songwriting assistant as a mobile app. Enables generating an entire songs sketch or just a section with a single tap. The music can be downloaded or exported as MIDI for easy loading in a DAW. (Length: Variable)"
  },
  {
    model: "Audialab",
    developer: "audialab.com",
    year: "2021",
    modality: "Audio",
    io: "Text → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "A collection of AI-powered generative tools: sample generator (Deep Sampler), drum sampler specialising in drum sound generator (Emergent Drums), sample pack generator (Infinite Packs), drum sound variation generator (Humanize). (Length: Short · Real-time)"
  },
  {
    model: "Boomy",
    developer: "boomy.com",
    year: "2019",
    modality: "Audio",
    io: "Audio/Text/Genre → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "A web portal allowing users to create original songs, sharing and monetizing them with full commercial rights. (Length: 1-2 mins / track)"
  },
  {
    model: "Loudly Generator",
    developer: "loudly.com",
    year: "2023",
    modality: "Audio",
    io: "Text/Metadata → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "Yes",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "Loudly Generator lets you select genre and other options to generate music or use a text prompt. The new beta version provides an option of including your own audio clips. (Length: 7 min)"
  },
  {
    model: "R-VAE",
    developer: "vigliensoni",
    year: "2022",
    modality: "Audio",
    io: "MIDI → MIDI",
    licenseType: "Fully Open",
    licenseName: "GPLv3",
    dataDisclosed: "Yes",
    dataSources: "\"The Future Sample Pack\"",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MIDI",
    openSource: "Yes",
    dataGap: "",
    notes: "Rhythm generator using Variational Autoencoder (VAE). Based on M4L.RhythmVAE by Nao Tokui, modded and extended to support simple and compound meter rhythms, with minimal amount of training data. Similarly to RhythmVAE, the goal of R-VAE is the exploration of latent spaces of musical rhythms. Unlike most previous work in rhythm modeling, R-VAE can be trained with small datasets, enabling rapid customization and exploration by individual users. R-VAE employs a data representation that encodes simple and compound meter rhythms. Models and latent space visualizations for R-VAE are available on the project's GitHub page: https://github.com/vigliensoni/R-VAE-models. (Technique: VAE · Length: 2 bars · Real-time)"
  },
  {
    model: "Magenta Continue",
    developer: "magenta.tensorflow.org",
    year: "2018",
    modality: "Audio",
    io: "MIDI → MIDI",
    licenseType: "Permissive",
    licenseName: "Apache 2.0",
    dataDisclosed: "Yes",
    dataSources: "MelodyRNN - Not disclosed; PerformanceRNN - The Piano- e-Competition dataset",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MIDI",
    openSource: "Yes",
    dataGap: "",
    notes: "Generates MIDI notes that are likely to follow the input drum beat or melody. Can extend the input of a specified MIDI clip by up to 32 measures. This can be helpful for adding variation to a drum beat or creating new material for a melodic track. It typically picks up on things like durations, key signatures and timing. It can be used to produce more random outputs by increasing the temperature. Ready to use as a Max for Live device. If you want to train the model on your own data or try different pre-trained models provided by the Magenta team, refer to the instructions on the team's GitHub page: https://github.com/magenta/magenta/tree/main/magenta/models/melody_rnn (Technique: LSTM · Length: 32 bars)"
  },
  {
    model: "Magenta Drumify",
    developer: "magenta.tensorflow.org",
    year: "2018",
    modality: "Audio",
    io: "MIDI → MIDI",
    licenseType: "Permissive",
    licenseName: "Apache 2.0",
    dataDisclosed: "Yes",
    dataSources: "Expanded Groove MIDI dataset; Groove MIDI dataset",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MIDI",
    openSource: "Yes",
    dataGap: "",
    notes: "Creates grooves based on the rhythm of any input. Can be used to generate a drum accompaniment to a bassline or melody, or to create a drum track from a tapped rhythm. Drumify works best with performed inputs, but it can also handle quantized clips. Ready to use as a Max for Live device. If you want to train the model on your own data or try different pre-trained models provided by the Magenta team, refer to the instructions on the team's GitHub page: https://github.com/magenta/magenta/tree/main/magenta/models/drums_rnn (Technique: LSTM · Length: Input length)"
  },
  {
    model: "Mubert",
    developer: "mubert.com",
    year: "2016",
    modality: "Audio",
    io: "Text/Genre/Metadata/Image → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "Yes",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "Platform for generating tracks, loops, mixes and jingles of length between 5 seconds to 5 minutes. The desired output can be prompted by a text or conditioned on an image (uploaded or linked to), or on additional information like genre, mood or activities. These labels can be chosen from a long list of predefined options. (Length: 5s-5min)"
  },
  {
    model: "MusicLM",
    developer: "google-research.github.io",
    year: "2023",
    modality: "Audio",
    io: "Text → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "Yes",
    dataSources: "MusicCaps, AudioSet",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "",
    notes: "Music generation from text descriptions developed by Google. The output can be prompted by a text description and additionally conditioned on a melody. (Technique: Transformer · Length: 30s)"
  },
  {
    model: "Okio Nendo",
    developer: "okio.ai",
    year: "2023",
    modality: "Audio",
    io: "Audio/Text → Audio",
    licenseType: "Permissive",
    licenseName: "MIT for core tools",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio",
    openSource: "Yes",
    dataGap: "Training data not disclosed",
    notes: "Open source platform capable of generating music from text prompts. (Technique: Suite of AI tools · Length: Variable · Real-time)"
  },
  {
    model: "Riffusion",
    developer: "riffusion.com",
    year: "2022",
    modality: "Audio",
    io: "Text/Image → Audio",
    licenseType: "Permissive",
    licenseName: "MIT",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Not specified",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "Audio",
    openSource: "Yes",
    dataGap: "Training data not disclosed",
    notes: "Music generation from text descriptions based on stable diffusion. Can be conditioned on an image. (Technique: Diffusion · Length: around 3min)"
  },
  {
    model: "SampleRNN",
    developer: "soroushmehr",
    year: "2016",
    modality: "Audio",
    io: "Audio → Audio",
    licenseType: "Permissive",
    licenseName: "MIT",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Not specified",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "Audio",
    openSource: "Yes",
    dataGap: "Training data not disclosed",
    notes: "WIP (Technique: Hierarchical Recurrent Neural Network (RNN) · Length: Variable)"
  },
  {
    model: "Soundful",
    developer: "soundful.com",
    year: "2023",
    modality: "Audio",
    io: "Text/Metadata → Audio/MIDI",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio/MIDI",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "An online platform for music generation based on a predefined genre or style. Users can select a format suitable for a specific type of content (eg. social media, gaming, vlogs), or type of output (eg. loops, sfx). (Length: 2.5min)"
  },
  {
    model: "Soundraw",
    developer: "soundraw.io",
    year: "2024",
    modality: "Audio",
    io: "Genre/Metadata → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "Yes",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "Music generation based on selected metadata on a proprietary web platform. Users can specify the length (from 10s to 5 min), tempo (slow, normal, fast) and select genre and/or mood, as well as a theme (corporate, ads, cinematic, etc.). (Length: 10s-5min)"
  },
  {
    model: "Splash Pro",
    developer: "splashmusic.com",
    year: "2023",
    modality: "Audio",
    io: "Text → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "Yes",
    dataSources: "Data collected and owned by Splash as well as data freely available under Creative Commons license",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "",
    notes: "Splash Pro is a platform for music generation from text descriptions. You can specify desired BPM and key. The platform contains a text-to-vocals model for synthesising realistic vocals. The output cn be downloaded in an MP3 format. From Splash's website: \"We have been developing our own proprietary technology and high quality audio datasets since 2017. Our AI research and capabilities include Text-to-Singing, Text-to-Rap, Generative Text-to-Music, Composition, Melody, Voice Transfer, Lyrics and Mastering.\" (Length: 30s-3min)"
  },
  {
    model: "Suno",
    developer: "suno.com",
    year: "2023",
    modality: "Audio",
    io: "Text → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "Full song generation from a text description. Can generate songs with lyrics. The generated songs can be then remixed or extended. (Length: around 2-4min)"
  },
  {
    model: "Udio",
    developer: "udio.com",
    year: "2024",
    modality: "Audio",
    io: "Audio/Text → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "Yes",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "Full song generation using text prompts. The songs can contain lyrics, prompted separately. The model can only be accessed through a proprietary platform which also offers clip and lyrics editing tools. (Length: 30s)"
  },
  {
    model: "WaveNet",
    developer: "deepmind.google",
    year: "2016",
    modality: "Audio",
    io: "Audio → Audio",
    licenseType: "Proprietary",
    licenseName: "Proprietary",
    dataDisclosed: "No",
    dataSources: "Not disclosed",
    attribution: "Not specified",
    commercialUse: "Proprietary terms",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "Audio",
    openSource: "No",
    dataGap: "Training data not disclosed",
    notes: "A model for generating speech and other audio signals like music developed by Google DeepMind. It uses raw waveforms which is more computationally expensive but produces more natural results. It was one of the early models using a CNN network to generate coherent musical structures. (Technique: Autoregressive Convolutional Neural Network · Length: Variable)"
  },
  {
    model: "Music2Latent",
    developer: "SonyCSLParis",
    year: "2024",
    modality: "Audio",
    io: "Audio → Audio",
    licenseType: "Restricted-Open",
    licenseName: "CC-BY-NC",
    dataDisclosed: "Yes",
    dataSources: "MTG Jamendo and DNS Challenge 4",
    attribution: "Not specified",
    commercialUse: "Not specified",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "Audio",
    openSource: "Yes",
    dataGap: "",
    notes: "Encode and decode audio samples to/from compressed representations! Useful for efficient generative modeling applications and for other downstream tasks. (Technique: Latent Consistency Model · Length: Variable / Audio input length · Real-time)"
  },
  {
    model: "Music FaderNets",
    developer: "music-fadernets.github.io",
    year: "2020",
    modality: "Audio",
    io: "MIDI → MIDI",
    licenseType: "Permissive",
    licenseName: "MIT",
    dataDisclosed: "Yes",
    dataSources: "VGMIDI, Yamaha Piano-e-Competition",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MIDI",
    openSource: "Yes",
    dataGap: "",
    notes: "Music FaderNets is a controllable MIDI generation framework that models high-level musical qualities, such as emotional attributes like arousal. Drawing inspiration from the concept of sliding faders on a mixing console, the model offers intuitive and continuous control over these characteristics. Given an input MIDI, Music FaderNets can produce multiple variations with different levels of arousal, adjusted according to the position of the fader. (Technique: VAE)"
  },
  {
    model: "Twoshot coproducer",
    developer: "twoshot.ai",
    year: "2025",
    modality: "Audio",
    io: "Audio/MIDI/Text/Genre/Metadata → Audio/MIDI",
    licenseType: "Mixed",
    licenseName: "Depends on inputs/models. Possible to generate royalty free content in many ways",
    dataDisclosed: "Yes",
    dataSources: "Proprietary licenced dataset",
    attribution: "Not specified",
    commercialUse: "Depends on components",
    finetune: "Yes",
    checkpoint: "No",
    api: "No",
    exportFormat: "Audio/MIDI",
    openSource: "No",
    dataGap: "",
    notes: "TwoShot's Coproducer is an all-in-one AI assistant that helps creators produce high-quality, commercially-safe audio. The platform enables users to: * Generate full tracks from hummed melodies or simple text prompts. * Remix existing songs, split audio into stems, and create unique samples. * Automatically score video scenes with context-aware sound effects. Designed for both beginners and professionals, The coproducer integrates seamlessly with industry-standard DAWs (e.g., Ableton, Logic) and is built on a 100% ethically-sourced, rights-cleared foundation. (Technique: Suite of AI tools)"
  },
  {
    model: "Mustango",
    developer: "amaai-lab.github.io",
    year: "2023",
    modality: "Audio",
    io: "Text → Audio",
    licenseType: "Mixed",
    licenseName: "MIT/CC-BY-SA",
    dataDisclosed: "Yes",
    dataSources: "MusicBench",
    attribution: "Not specified",
    commercialUse: "Depends on components",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "Audio",
    openSource: "Yes",
    dataGap: "",
    notes: "Mustango is an open-source Text-to-Music model with focus on fine controllability allowing to specify musical attributes such as key or chord sequences. (Technique: Latent Diffusion · Length: 10 sec)"
  },
  {
    model: "Calliope",
    developer: "metacreation.net",
    year: "2022",
    modality: "Audio",
    io: "MIDI → MIDI",
    licenseType: "Permissive",
    licenseName: "Apache 2.0",
    dataDisclosed: "Yes",
    dataSources: "MetaMIDI",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "No",
    checkpoint: "No",
    api: "No",
    exportFormat: "MIDI",
    openSource: "No",
    dataGap: "",
    notes: "Calliope is used to generate new multi-track MIDI content from existing MIDI files or to generate from scratch. This is achieved via musical inpainting by selecting bars to be re-generated and a destination instrument which will play the generated content (e.g. trumpet, drums, violin or piano). This influences the model generation because composing for a drums section is a different task than composing for a string section. Calliope offers a unique creative workflow where you can generate variations in batch. This allows to choose from many generations. Calliope is aimed at both amateur and professional users. (Technique: Transformer)"
  },
  {
    model: "Yue AI",
    developer: "map-yue.github.io",
    year: "2025",
    modality: "Audio",
    io: "Audio/Text → Audio",
    licenseType: "Permissive",
    licenseName: "Apache-2.0 license",
    dataDisclosed: "Yes",
    dataSources: "WeNetSpeech, LibriHeavy, GigaSpeech, 650K hours of internet mined data",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "Audio",
    openSource: "Yes",
    dataGap: "",
    notes: "Yue AI is an open-source music generation model. The user can input lyrics and genre information as text, along with optional audio clips for context, with the input audio clips needing to be around 30 seconds long. Supported input languages include English, Mandarin Chinese, Cantonese, Japanese, and Korean. Yue AI will output its generated music in an audio file that is up to 5 minutes in length. (Technique: Transformer · Length: 5 minutes)"
  },
  {
    model: "DiffRhythm",
    developer: "aslp-lab.github.io",
    year: "2025",
    modality: "Audio",
    io: "Audio/Text → Audio",
    licenseType: "Permissive",
    licenseName: "Apache-2.0 license",
    dataDisclosed: "Yes",
    dataSources: "300,000 hours of internet scraped music, cleaned to 25,000 hours of top-quality music",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "Audio",
    openSource: "Yes",
    dataGap: "",
    notes: "DiffRhythm is an open-source music generation model. The user can input lyrics and style information as text, along with an optional audio prompt for context, with the input audio clips needing to be less than 10 seconds long. Supported languages include English and Chinese. DiffRhythm will output its generated music as an audio file (MP3, wav, or ogg) that is up to 285 seconds in length. (Technique: Latent Diffusion · Length: 95-285 seconds)"
  },
  {
    model: "Muzic ROC",
    developer: "microsoft",
    year: "2022",
    modality: "Audio",
    io: "Text → MIDI",
    licenseType: "Permissive",
    licenseName: "MIT License",
    dataDisclosed: "Yes",
    dataSources: "LMD-matched MIDI dataset",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MIDI",
    openSource: "Yes",
    dataGap: "",
    notes: "Muzic ROC is an open-source music generation model. The user can input lyrics and a chord progression as text, and the model will output a melody. ROC is language-insensitive, so slightly editing the code can modify its output language. (Length: dependent on lyrics provided)"
  },
  {
    model: "SongGen",
    developer: "liuzh-19.github.io",
    year: "2025",
    modality: "Audio",
    io: "Audio/Text → Audio",
    licenseType: "Permissive",
    licenseName: "Apache-2.0 license",
    dataDisclosed: "Yes",
    dataSources: "8,000 hours of audio from Million Song Dataset (MSD), Free Music Archive (FMA), and MTG-Jamendo Dataset",
    attribution: "Not specified",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "Audio",
    openSource: "Yes",
    dataGap: "",
    notes: "SongGen is an open-source music generation model. The user can input lyrics and description information as text, along with an optional audio clip of voice for cloning, with the input audio clip needing to be around 3 seconds. SongGen will output its generated music in an audio file that is up to 30 seconds in length. (Technique: Transformer · Length: 30 seconds)"
  }
];
