const MODELS = [
  {
    model: "Stable Diffusion 3.5",
    developer: "Stability AI",
    year: "2024",
    modality: "Image",
    io: "Text/Image → Image",
    licenseType: "Restricted-Open",
    licenseName: "Stability AI Community License",
    dataDisclosed: "No",
    dataSources: "LAION-5B subset + proprietary data; specific composition undisclosed",
    attribution: "None",
    commercialUse: "Yes (<$1M revenue)",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "PNG, JPG, WebP",
    openSource: "Yes",
    dataGap: "Training data sourced from web scrape without creator consent; no attribution tool; revenue threshold gate",
    notes: "Most widely deployed open image model. LAION dataset faced copyright lawsuits (Getty v. Stability AI)."
  },
  {
    model: "FLUX.1 (Schnell/Dev)",
    developer: "Black Forest Labs",
    year: "2024",
    modality: "Image",
    io: "Text → Image",
    licenseType: "Mixed",
    licenseName: "Apache 2.0 (Schnell); Non-commercial (Dev); Proprietary (Pro)",
    dataDisclosed: "No",
    dataSources: "Undisclosed; founded by ex-Stability AI team",
    attribution: "None",
    commercialUse: "Yes (Schnell only)",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "PNG, JPG, WebP",
    openSource: "Yes",
    dataGap: "Apache Schnell variant is open but training data fully undisclosed; split licensing model creates confusion",
    notes: "State-of-the-art quality in 2024-25. Schnell = best open image model. Data provenance = black box."
  },
  {
    model: "Stable Diffusion XL",
    developer: "Stability AI",
    year: "2023",
    modality: "Image",
    io: "Text/Image → Image",
    licenseType: "Restricted-Open",
    licenseName: "CreativeML Open RAIL-M",
    dataDisclosed: "Partial",
    dataSources: "LAION-5B (partially documented) + additional proprietary data",
    attribution: "None (LAION documented sources but no per-image attribution)",
    commercialUse: "Yes (with attribution)",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "PNG, JPG, SafeTensors, GGUF",
    openSource: "Yes",
    dataGap: "RAIL-M restricts harmful use but no attribution for training artists; LAION lawsuit pending",
    notes: "RAIL-M was first attempt at responsible use license for diffusion models. Key reference."
  },
  {
    model: "DeepFloyd IF",
    developer: "Stability AI / DeepFloyd",
    year: "2023",
    modality: "Image",
    io: "Text → Image",
    licenseType: "Restricted-Open",
    licenseName: "DeepFloyd IF Research License",
    dataDisclosed: "No",
    dataSources: "LAION-5B + Conceptual Captions",
    attribution: "None",
    commercialUse: "No",
    finetune: "Partial",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "PNG",
    openSource: "Yes",
    dataGap: "Research-only license; LAION data issues; cascade model requires significant compute",
    notes: "Pioneered pixel-space cascade diffusion. Research-only use limits applicability."
  },
  {
    model: "StyleGAN / StyleGAN3",
    developer: "NVIDIA",
    year: "2019-2021",
    modality: "Image",
    io: "Latent → Image (face-specialized)",
    licenseType: "Restricted-Open",
    licenseName: "NVIDIA Source Code License",
    dataDisclosed: "Partial",
    dataSources: "FFHQ (Flickr Faces HQ - scraped Flickr); LSUN; AFHQ",
    attribution: "FFHQ dataset published with provenance; faces from Flickr under CC license",
    commercialUse: "Partial",
    finetune: "Partial",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "PNG, TFRecord",
    openSource: "Yes",
    dataGap: "Flickr data scraped without explicit AI consent; faces of real people; NVIDIA non-commercial clauses",
    notes: "Best-in-class for photorealistic faces. FFHQ documentation = good data provenance example."
  },
  {
    model: "AnimateDiff",
    developer: "Shanghai AI Lab",
    year: "2023",
    modality: "Video",
    io: "Text/Image → Video",
    licenseType: "Permissive",
    licenseName: "Apache 2.0",
    dataDisclosed: "No",
    dataSources: "WebVid-10M + internal data; sources partially cited",
    attribution: "None",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MP4, GIF",
    openSource: "Yes",
    dataGap: "Training data partially cited but no attribution; runs on SD base = inherits SD data issues",
    notes: "Plug-in motion module for SD. Apache license but inherits Stable Diffusion data IP issues."
  },
  {
    model: "Open-Sora (HPC-AI Tech)",
    developer: "HPC-AI Tech",
    year: "2024",
    modality: "Video",
    io: "Text → Video",
    licenseType: "Fully Open",
    licenseName: "Apache 2.0",
    dataDisclosed: "Full",
    dataSources: "HD-VG-130M, Panda-70M, WebVid-10M - all documented",
    attribution: "Dataset documentation published; sources cited",
    commercialUse: "Full",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MP4",
    openSource: "Yes",
    dataGap: "WebVid license restricts commercial use of trained models; data source mix has IP complexity",
    notes: "Most transparent open video model. Data docs set a good standard despite licensing mix."
  },
  {
    model: "Wan 2.1 (Alibaba)",
    developer: "Alibaba",
    year: "2025",
    modality: "Video",
    io: "Text/Image → Video",
    licenseType: "Permissive",
    licenseName: "Apache 2.0",
    dataDisclosed: "No",
    dataSources: "Undisclosed",
    attribution: "None",
    commercialUse: "Yes",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "MP4",
    openSource: "Yes",
    dataGap: "Complete data opacity despite Apache license; state-of-the-art video quality",
    notes: "Best open video model quality as of early 2025. Data provenance entirely opaque."
  },
  {
    model: "MusicGen (Meta)",
    developer: "Meta AI",
    year: "2023",
    modality: "Audio",
    io: "Text/Melody → Music",
    licenseType: "Restricted-Open",
    licenseName: "CC BY-NC 4.0",
    dataDisclosed: "Partial",
    dataSources: "Licensed music dataset (~20K hours; licensed tracks, not public domain)",
    attribution: "Dataset of licensed music used; license holder list partially disclosed",
    commercialUse: "Partial",
    finetune: "No",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "WAV, MP3",
    openSource: "Yes",
    dataGap: "NC license; dataset included licensed tracks - sets precedent for licensed training data model; no per-track attribution output",
    notes: "Key precedent: used properly licensed training data. NC restriction is limiting. Good model card."
  },
  {
    model: "AudioCraft / EnCodec",
    developer: "Meta AI",
    year: "2023",
    modality: "Audio",
    io: "Text → Audio/Music",
    licenseType: "Restricted-Open",
    licenseName: "CC BY-NC 4.0",
    dataDisclosed: "Partial",
    dataSources: "AudioSet, FreeSound, Shutterstock (licensed); some unlicensed web audio",
    attribution: "Partial source list; no per-sample attribution",
    commercialUse: "Partial",
    finetune: "No",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "WAV, encodec tokens",
    openSource: "Yes",
    dataGap: "NC license limits commercial use; mixed licensed/unlicensed training data; no attribution output",
    notes: "Best open music generation pipeline. NC + mixed data provenance = key gap for commercial projects."
  },
  {
    model: "Dance Diffusion (Harmonai)",
    developer: "Harmonai / Stability AI",
    year: "2022",
    modality: "Audio",
    io: "Audio → Audio",
    licenseType: "Fully Open",
    licenseName: "MIT",
    dataDisclosed: "Full",
    dataSources: "Online sources: glitch.cool, songaday.world, MAESTRO, Unlocked Recordings, xeno-canto",
    attribution: "All sources listed in documentation",
    commercialUse: "Full",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "WAV",
    openSource: "Yes",
    dataGap: "Source list published but consent status unclear for scraped sites; no output attribution",
    notes: "MIT license + documented sources = good model. Matches gen-ai-for-music.alwaysdata.net entry."
  },
  {
    model: "RAVE (IRCAM)",
    developer: "IRCAM / Antoine Caillon",
    year: "2022",
    modality: "Audio",
    io: "Audio → Audio (realtime VAE)",
    licenseType: "Fully Open",
    licenseName: "MIT",
    dataDisclosed: "Full",
    dataSources: "User-provided (train on your own data); no fixed dataset",
    attribution: "User controls training data - strongest possible attribution model",
    commercialUse: "Full",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "WAV, Max/MSP, PureData",
    openSource: "Yes",
    dataGap: "Train-your-own model: user must ensure their data rights. No centralized dataset = no centralized IP issue.",
    notes: "Excellent model for artists training on their own archives. Fits project ethos perfectly."
  },
  {
    model: "AudioLCM",
    developer: "University researchers",
    year: "2023",
    modality: "Audio",
    io: "Text → Audio",
    licenseType: "Fully Open",
    licenseName: "MIT",
    dataDisclosed: "Partial",
    dataSources: "AudioCaps dataset + undisclosed teacher model",
    attribution: "AudioCaps documented; teacher model not disclosed",
    commercialUse: "Partial",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "No",
    exportFormat: "WAV",
    openSource: "Yes",
    dataGap: "Teacher model provenance unknown; otherwise well-documented",
    notes: "Efficient latent consistency model. Good starting point for licensed audio generation."
  },
  {
    model: "Stable Audio Open",
    developer: "Stability AI",
    year: "2024",
    modality: "Audio",
    io: "Text → Audio/Music",
    licenseType: "Fully Open",
    licenseName: "Apache 2.0",
    dataDisclosed: "Partial",
    dataSources: "Freesound dataset (~800K clips, Creative Commons licensed)",
    attribution: "Freesound = CC-licensed, documented; metadata retained in dataset",
    commercialUse: "Partial",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "WAV, FLAC",
    openSource: "Yes",
    dataGap: "Freesound CC licenses vary (some NC, some commercial) - aggregate license unclear; no per-output attribution",
    notes: "Key model: trained on CC-licensed audio. Closest to ethically-sourced generative audio for this project."
  },
  {
    model: "LUKE FAKE ENTRY",
    developer: "Stability AI",
    year: "2026",
    modality: "Audio",
    io: "Text → Audio/Music",
    licenseType: "Fully Open",
    licenseName: "Apache 2.0",
    dataDisclosed: "Partial",
    dataSources: "Freesound dataset (~800K clips, Creative Commons licensed)",
    attribution: "Freesound = CC-licensed, documented; metadata retained in dataset",
    commercialUse: "Partial",
    finetune: "Yes",
    checkpoint: "Yes",
    api: "Yes",
    exportFormat: "WAV, FLAC",
    openSource: "Yes",
    dataGap: "Freesound CC licenses vary (some NC, some commercial) - aggregate license unclear; no per-output attribution",
    notes: "Key model: trained on CC-licensed audio. Closest to ethically-sourced generative audio for this project."
  }
];
